# Use the official lightweight Nginx image
FROM nginx:alpine

# Create a simple custom index.html file inside the container
RUN echo "<h1>Hello from AWS ECR Lab!</h1>" > /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80